### ISSUE TITLE
Scala 2.12 release artifact for 1.0.0-RC1 is empty

### ISSUE THREAD

**Issue by seglo** [VladKopanev/cats-saga#152]
I tried referencing this library in a 2.12 project, but the jar it pulls down contains nothing other than jar metadata.

https://search.maven.org/artifact/com.vladkopanev/cats-saga_2.12/1.0.0-RC1/jar

**Comment by VladKopanev** [comment]
Hey @seglo I'm sorry for the long response time, yeah you are right, I've checked and for some reason, the artefact for 2.12 is empty when downloaded from maven, this is strange because publishLocal produces a fully packed jar! I think maybe it has something to do with "sbt-release-early" plugin, that plugin looks like it is not supported anymore and maybe has some incompatibilities with the latest sbt version released when used against scala 2.12. Unfortunately, this issue is hard to investigate right now, and also to fix as the plugin is not supported anymore, and the only solution I see is to migrate to release plugins that are still supported. Pls, let me know if this is crucial for you to have a release for 2.12 and you can't migrate to new Scala versions and I will try to do something about it.

**Comment by seglo** [comment]
No worries! I found an alternative on the project I was working on at the time.
